export enum AttachmentType {
    THESIS = 'THESIS',
    SOURCE_CODE = 'SOURCE_CODE',
    PHOTO = 'PHOTO',
    MANUAL_USAGE = 'MANUAL_USAGE',
    MANUAL_STARTUP = 'MANUAL_STARTUP',
    OTHER = 'OTHER'
}
